### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mcollina**
* Updated archiver to 0.14.x to avoid deprecation warning
* Updated istanbul to 0.3.x
* Updated body-parser to 1.12.x

### CODE REVIEW

**Comment by lpinca** [comment]
Any chance to get this merged?
The build seems to fail because express 4 does not support node 0.8 (`setImmediate` is not available).

**Comment by feross** [comment]
+1

**Comment by gillesdemey** [comment]
We can even update to `archiver@1.15.x` if you change

```javascript
var stream = archiver.createZip(),
```

to 

```javascript
var stream = archiver.create('zip'),
```

in `lib/handler.js:92` since that was deprecated.

https://github.com/archiverjs/node-archiver/blob/1e55f081f0ad96622990da016e7f1ea091143c16/lib/archiver.js#L43

**Comment by abstractj** [comment]
@gotwarlost Any chance of getting this merged? This PR fixes the following security vulnerabilities:

- https://nodesecurity.io/advisories/uglifyjs_incorrectly_handles_non-boolean_comparisons
- https://nodesecurity.io/advisories/qs_dos_extended_event_loop_blocking
- https://nodesecurity.io/advisories/qs_dos_memory_exhaustion

**Comment by mcollina** [comment]
cc @davglass

**Comment by davglass** [comment]
I'm not a collaborator on this repo, but I'll get @gotwarlost to get this done :)

**Comment by abstractj** [comment]
@davglass thanks a lot!

**Comment by mcollina** [comment]
@davglass thanks! :)

**Comment by gotwarlost** [comment]
Once @davglass is on the case, things happen :) 

Sorry for the delay. I'm going to ignore the build failure for `0.8` and merge this.

**Comment by abstractj** [comment]
@gotwarlost @davglass thanks a lot! Do you guys have any plans to publish a version 0.2.1 or something like that on npmjs.org?

**Comment by gotwarlost** [comment]
Done

**Pull request merged**
