### PR TITLE
updating archiver dependency

### PR DESCRIPTION
**Pull request by maxmil7**
Fix for #31 
Tested it locally. I was able to download the zip file w/o any issues.

### CODE REVIEW

**Comment by shaunwarman** [comment]
👍  @gotwarlost 

https://github.com/archiverjs/node-archiver#usage

**Comment by linkRace** [comment]
Also leaving a 👍 on this, is this repo still being maintained?

**Comment by mcollina** [comment]
@gotwarlost?

**Comment by nagapavan** [comment]
Any update on when this PR will be merged?
This will address the Security issue "https://nodesecurity.io/advisories/118", with Minimatch.

**Comment by maxmil7** [comment]
Closing this in favor of #40

**Pull request closed without merging**
